Frontend:
  impl: LoadStoreTrace
  clock_ratio: 1
  debug: true

Translation:
  impl: RandomTranslation
  max_addr: 2147483648     

MemorySystem:
  impl: BHDRAMSystem
  clock_ratio: 3

  DRAM:
    impl: DDR5-VRR
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN 
    RFM:
      BRC: 2
    PRAC: true

  BHDRAMController:
    impl: PRACDRAMController
    BHScheduler:
      impl: PRACScheduler
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    debug: true

    plugins:
      - ControllerPlugin:
          impl: PRAC
          abo_delay_acts: 4
          abo_recovery_refs: 4
          abo_act_ns: 180
          abo_threshold: 32
          debug: false

  AddrMapper:
    impl: RoBaRaCoCh
